SELECT
    STRATEGY,
    CAST(DATE AS DATE)                 AS RETURN_DATE,
    CAST(DAILY_RETURN AS FLOAT64)      AS DAILY_RETURN
FROM {{ source('raw', 'RAW_BACKTEST_RETURNS') }}
WHERE DAILY_RETURN IS NOT NULL
