SELECT
    STRATEGY,
    CAST(REBALANCE_DATE AS DATE)       AS REBALANCE_DATE,
    CAST(TURNOVER AS FLOAT64)          AS TURNOVER,
    CAST(COST AS FLOAT64)              AS COST,
    CAST(N_HOLDINGS AS INT64)          AS N_HOLDINGS
FROM {{ source('raw', 'RAW_BACKTEST_TURNOVER') }}
